# Generated by Django 4.2.1 on 2023-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('catalog_info', models.CharField(max_length=300, verbose_name='Описание')),
                ('catalog_image', models.ImageField(blank=True, null=True, upload_to='catalogs/', verbose_name='Изображение')),
                ('catalog_category', models.CharField(max_length=200, verbose_name='Категория')),
                ('catalog_buy_price', models.FloatField(max_length=20, verbose_name='Цена за покупку')),
                ('catalog_create_date', models.DateField(verbose_name='Дата создания')),
                ('catalog_last_upd_dt', models.DateField(verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category_info', models.CharField(max_length=300, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
