# Generated by Django 4.2.1 on 2023-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('product_info', models.CharField(max_length=300, verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('product_category', models.CharField(max_length=200, verbose_name='Категория')),
                ('product_price', models.FloatField(max_length=20, verbose_name='Цена')),
                ('product_create_date', models.DateField(verbose_name='Дата создания')),
                ('product_last_upd_dt', models.DateField(verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
