# Generated by Django 4.2.1 on 2023-05-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('blog_slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('blog_content', models.TextField(verbose_name='Содержимое')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Превью (изображение)')),
                ('blog_create_date', models.DateField(verbose_name='Дата создания')),
                ('blog_publicate_flg', models.BooleanField(verbose_name='Признак публикации')),
                ('blog_views_count', models.IntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
