# Generated by Django 4.2.1 on 2023-05-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
