# Generated by Django 4.2.1 on 2023-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_blog_blog_content_alter_blog_blog_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('active', 'Активный'), ('archive', 'В архиве'), ('await', 'На модерации')], default='active', max_length=10),
        ),
    ]
