# Generated by Django 4.2.1 on 2023-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('active', 'Активный'), ('archive', 'В архиве'), ('await', 'На модерации')], default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
