# Generated by Django 4.2.1 on 2023-06-05 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_create_date',
            field=models.DateField(default=datetime.date(2023, 6, 5), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_last_upd_dt',
            field=models.DateField(default=datetime.date(2023, 6, 5), verbose_name='Дата последнего изменения'),
        ),
    ]
