# Generated by Django 4.2.1 on 2023-06-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_product_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='number',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Номер версии'),
        ),
    ]
