# Generated by Django 4.2.1 on 2023-06-11 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productversion_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_create_date',
            field=models.DateField(default=datetime.date(2023, 6, 11), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_last_upd_dt',
            field=models.DateField(default=datetime.date(2023, 6, 11), verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт'),
        ),
    ]
