# Generated by Django 4.2.1 on 2023-06-14 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_product_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_status_product', 'Can publish product'), ('change_info_product', 'Can change product info'), ('change_category_product', 'Can change product category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_create_date',
            field=models.DateField(default=datetime.date(2023, 6, 14), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_last_upd_dt',
            field=models.DateField(default=datetime.date(2023, 6, 14), verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('no active', 'Не активный'), ('active', 'Активный'), ('archive', 'В архиве'), ('await', 'На модерации')], default='no active', max_length=10, verbose_name='Статус'),
        ),
    ]
